### PR TITLE
Release 1.6.2

### PR DESCRIPTION
**Pull request by charvolant**
Minor updates to logging configuration and structure.
Use openjdk8 on travis

### CODE REVIEW

**Comment by ansell** [comment]
I am wondering what the logging strategy will be. I removed logback, and you removed the SLF4J Log4J library, so not sure how SLF4J log messages will be processed.

**Comment by charvolant** [comment]
> I am wondering what the logging strategy will be. I removed logback, and you removed the SLF4J Log4J library, so not sure how SLF4J log messages will be processed.

That might explain the singular lack of a log in /var/log/tomcat9 Since grails uses logback, my instinct is to use logback?

**Comment by ansell** [comment]
The logback exclusions were all done in a single place, so they can be reverted easily: https://github.com/AtlasOfLivingAustralia/sds-webapp2/pull/10/files#diff-c197962302397baf3a4cc36463dce5eaR31-R38

**Comment by charvolant** [comment]
> The logback exclusions were all done in a single place, so they can be reverted easily: https://github.com/AtlasOfLivingAustralia/sds-webapp2/pull/10/files#diff-c197962302397baf3a4cc36463dce5eaR31-R38

I'll give it a try and see if it works.

**Comment by charvolant** [comment]
I've reintroduced logback and set up a configuration that will generate an sds.log (Tested on sds-test.ala.org.au)

**Review by ansell — APPROVED** [review]
The new logging setup looks good.

**Pull request merged**
